### ISSUE TITLE
editline compilation (no_gpl)

### ISSUE THREAD

**Issue by ahoarau** [orocos-toolchain/ocl#64]
I failed to compile ocl with -DNO_GPL and having editline installed.
```
orocos_toolchain/ocl/taskbrowser/TaskBrowser.cpp:209:37: error: use of undeclared identifier 'RL_STATE_READCMD'
                return (RL_ISSTATE (RL_STATE_READCMD) ? READERR : EOF);
                                    ^
orocos_toolchain/ocl/taskbrowser/TaskBrowser.cpp:209:57: error: use of undeclared identifier 'READERR'
                return (RL_ISSTATE (RL_STATE_READCMD) ? READERR : EOF);
                                                        ^
orocos_toolchain/ocl/taskbrowser/TaskBrowser.cpp:215:37: error: use of undeclared identifier 'RL_STATE_READCMD'
                return (RL_ISSTATE (RL_STATE_READCMD) ? READERR : EOF);
                                    ^
orocos_toolchain/ocl/taskbrowser/TaskBrowser.cpp:215:57: error: use of undeclared identifier 'READERR'
                return (RL_ISSTATE (RL_STATE_READCMD) ? READERR : EOF);
```

Here's my configuration : 
```
-- Looking for curses implementation - found libncurses
-- Looking for readline/readline.h - found
-- Looking for editline/readline.h - found
Setting LOG4CPP_ROOT to orocos-toolchain_ws/install
Found orocos-log4cpp in orocos-toolchain_ws/install/include/orocos
Building TaskBrowser with editline support.
```

ps: with readline it builds fine

**Comment by meyerj** [comment]
I added a bugfix in #65, which has been tested in Ubuntu 16.04 with `libedit2`/`libedit-dev` version 3.1-20150325-1ubuntu2. Thanks for reporting this regression, which I introduced in https://github.com/orocos-toolchain/ocl/pull/7!
